### ISSUE TITLE
[GUI] Hide Toolbox menu

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/hydromt_fiat#236]

**Comment by kathrynroscoe** [comment]
This is to hide toolboxes that are not active/will not work for the model-builder users, to avoid confusion. @roeldegoede  - please determine which these are for the SFINCS model-builder and hide them, and @Santonia27 same for Delft-FIAT model builder. I understand that this is a very easy task. If that is not the case, we can re-evaluate the March milestone.

**Comment by roeldegoede** [comment]
I think the initial issue is a bit different than described by Kathryn.

For the FloodAdapt model builder, we are basically only using the "Model Maker" toolbox, since the other toolboxes like "observation stations" and "watershed" toolboxes are now implemented as popups. This makes the "Toolbox" button itself abundant. 

I think the idea was to check whether we had only have one type of toolbox (that can be multiple model makers), and if that's the case, Frederique wanted to hide the "Toolbox" button

**Comment by LuukBlom** [comment]
hide if its only one value in the menu tab

**Comment by savente93** [comment]
this is marked as done, so closing it
